// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Beli(arg1:string,arg2:string):Promise<main.StatusTransksi>;

export function DapatinAkun():Promise<main.Akun>;

export function Greet(arg1:string):Promise<string>;

export function Jual(arg1:string,arg2:string):Promise<main.StatusTransksi>;

export function Login(arg1:string,arg2:string):Promise<main.StatusAutentikasi>;

export function Portfolio():Promise<Array<main.Transaksi>>;

export function Register(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.StatusAutentikasi>;
